# https://rust-lang.github.io/rustfmt/?version=v1.4.38&search=

# indent_style = "Block"
# reorder_imports = false

use_small_heuristics = "Off"
comment_width = 80
max_width = 80
fn_call_width = 80
attr_fn_like_width = 80
struct_lit_width = 80
struct_variant_width = 80
array_width = 80
chain_width = 80
single_line_if_else_max_width = 80

reorder_impl_items = true
reorder_imports = true
# group_imports = "StdExternalCrate"

# ! Temporarily trying out braces on same line
brace_style = "AlwaysNextLine"
control_brace_style = "AlwaysNextLine"
merge_derives = true
indent_style = "Block"
combine_control_expr = false
fn_params_layout = "Tall"
condense_wildcard_suffixes = true
spaces_around_ranges = true
wrap_comments = false
blank_lines_upper_bound = 1
newline_style = "Unix"
overflow_delimited_expr = true
